### ISSUE TITLE
Default cachePath for MacOS

### ISSUE THREAD

**Issue by anuragiiits** [carlosascari/chrome-cache-reader#2]
I tried giving the cachePath `${ os.homedir() }/Library/Caches/Chromium` in my MacOS but I am always getting `null` value for the chromeCacheFile.  
What should be the path for the MacOS using Chromium based browser?

**Comment by carlosascari** [comment]
Check here https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md

it says:

```
[Chromium] ~/Library/Application Support/Chromium
```
So you could check there, what you need to find is a bunch of files in a directory where each file has a http response and the data. Chrome/Chromium caches everything including the http response into a file.

I don't use MacOS so I can't confirm, if it is so, please let me know or add the information to the README if you'd like

**Comment by anuragiiits** [comment]
As per the [documentation](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#user-cache-directory), I tried giving the path as `~/Library/Caches/Google/Chrome/Default` for the Chrome browser.  
Now, I'm getting an error as opposed to earlier null response.
The error is:
```
(libuv) kqueue(): Too many open files
(libuv) kqueue(): Too many open files
tty.js:93
    throw new ERR_TTY_INIT_FAILED(ctx);
    ^

SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EMFILE (too many open files)
    at new WriteStream (tty.js:93:11)
    at createWritableStdioStream (internal/bootstrap/switches/is_main_thread.js:47:16)
    at process.getStderr [as stderr] (internal/bootstrap/switches/is_main_thread.js:134:12)
    at Object.get (internal/console/constructor.js:202:44)
    at Object.value (internal/console/constructor.js:312:50)
    at Object.warn (internal/console/constructor.js:346:61)
    at writeOut (internal/process/warning.js:41:3)
    at process.onWarning (internal/process/warning.js:101:3)
    at process.emit (events.js:314:20)
    at doEmitWarning (internal/process/warning.js:66:11) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -24,
    code: 'EMFILE',
    message: 'too many open files',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
```

**Comment by carlosascari** [comment]
I suppose you are using a cache that has many tens of thousands of files already. 

https://github.com/carlosascari/chrome-cache-reader/blob/master/index.js#L148

All files are opened simultaneously when there is an *update*, I suppose the maximum allowed opened files on the operating system is being exceeded.

Here are some options:

1. If you want to progress now, you could delete your cache and start fresh, otherwise 
2. You can update the maximum number of files that can be opened by your OS.  
3. Update the code so as to open files in series (blocking) this will minimize the number of opened files at one time:
This [line]( https://github.com/carlosascari/chrome-cache-reader/blob/master/index.js#L143) is called in parallel by the number of files in your cache
